#Stage for doing Java build

FROM registry.access.redhat.com/ubi8 as javabuilder

WORKDIR /opt

ADD Java_OpenJDK22.tar.gz .

RUN /opt/Java_OpenJDK22/bin/java -version

COPY Simple.java .

RUN /opt/Java_OpenJDK22/bin/javac /opt/Simple.java

RUN ls -lrt /opt/Java_OpenJDK22/bin/java && ls -lrt /opt

#Stage 2 for Container Image
FROM registry.access.redhat.com/ubi8

LABEL Arun prabhu.arun10@gmail.com
LABEL project="Arun'sProject"

ARG VERSION \
    DEVELOPER

ENV PROJECT="DEMO PROJECT" \
    ENV_VERSION=${VERSION:-0.1} \
    ENV_DEVELOPER=${DEVELOPER:-Demo}

WORKDIR /opt

ADD Java_OpenJDK22.tar.gz .

ENV JAVA_HOME=/opt/Java_OpenJDK22
COPY --from=javabuilder /opt/Simple.class /opt/

#Execute my script while starting container
ENTRYPOINT ["/opt/Java_OpenJDK22/bin/java"]

CMD ["-version"]
